AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
